---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#PCA

```{r}
load("TrainData.Rdata")

X <- read.table(file="trainX.txt",header=TRUE)
y <- read.table(file="trainy.txt",header=TRUE)
res <- prcomp(X, t(Y))
plot(cumsum(res$sdev^2/sum(res$sdev^2))) #cumulative explained variance
```

#hierarchical cluster

```{r}
k2 <- kmeans(res$x[,1:10], centers = 2, iter.max = 100, nstart = 10, 
                algorithm = "Lloyd")
x_df <- data.frame(res$x[,1:10], cluster = as.factor((k2$cluster - 2)*-1))

sum(x_df$cluster != trainY) / 133

#Average Linkage
acluster <- hclust(dist(data.frame(x_df)), method = "average")
plot(acluster)
aclusterCut <- cutree(acluster, 3)
table(aclusterCut, trainY)
sum(aclusterCut != trainY) / 133

#Single Linkage
scluster <- hclust(dist(data.frame(x_df)), method = "single")
plot(scluster)
sclusterCut <- cutree(scluster, 3)
table(sclusterCut, trainY)
sum(sclusterCut != trainY) / 133

#Complete Linkage
ccluster <- hclust(dist(data.frame(x_df)), method = "complete")
plot(ccluster)
cclusterCut <- cutree(ccluster, 3)
table(cclusterCut, trainY)
sum(cclusterCut != trainY) / 133
```


```{r}
#Average Linkage
arcluster <- hclust(dist(data.frame(x_df)), method = "average")
plot(arcluster, main = "Non-PCA Average Hierarchical Clustering", xlab = "")
arclusterCut <- cutree(arcluster, 2)
arclusterCut[arclusterCut == 1] = 0
arclusterCut[arclusterCut == 2] = 1
print("Non-PCA Average Hierarchical Classifcation Error: "); sum(arclusterCut != trainY) / 133

acluster <- hclust(dist(data.frame(trainX)), method = "average")
plot(acluster, main = "Average Hierarchical Clustering", xlab = "")
aclusterCut <- cutree(acluster, 2)
aclusterCut[aclusterCut == 1] = 0
aclusterCut[aclusterCut == 2] = 1
print("Average Hierarchical Classifcation Error: "); sum(aclusterCut != trainY) / 133

#Single Linkage
srcluster <- hclust(dist(data.frame(x_df)), method = "single")
plot(scluster, main = "Non-PCA Single Hierarchical Clustering", xlab = "")
srclusterCut <- cutree(srcluster, 2)
srclusterCut[srclusterCut == 1] = 0
srclusterCut[srclusterCut == 2] = 1
print("Non-PCA Single Hierarchical Classifcation Error: "); sum(srclusterCut != trainY) / 133

scluster <- hclust(dist(data.frame(trainX)), method = "single")
plot(scluster, main = "Single Hierarchical Clustering", xlab = "")
sclusterCut <- cutree(scluster, 2)
sclusterCut[sclusterCut == 1] = 0
sclusterCut[sclusterCut == 2] = 1
print("Single Hierarchical Classifcation Error: "); sum(sclusterCut != trainY) / 133

#Complete Linkage
crcluster <- hclust(dist(data.frame(x_df)), method = "complete")
plot(crcluster, main = "Non-PCA Complete Hierarchical Clustering", xlab = "")
crclusterCut <- cutree(crcluster, 2)
crclusterCut[crclusterCut == 1] = 0
crclusterCut[crclusterCut == 2] = 1
print("Non-PCA Complete Hierarchical Classifcation Error: "); sum(crclusterCut != trainY) / 133

ccluster <- hclust(dist(data.frame(trainX)), method = "complete")
plot(ccluster, main = "Complete Hierarchical Clustering", xlab = "")
cclusterCut <- cutree(ccluster, 2)
cclusterCut[cclusterCut == 1] = 0
cclusterCut[cclusterCut == 2] = 1
print("Complete Hierarchical Classifcation Error: "); sum(cclusterCut != trainY) / 133
```
